version: 2.1

orbs:
  kitchen: sous-chefs/kitchen@1.0.0
executors:
  ruby:
    docker: [ image: circleci/ruby ]

jobs:
  lint_ruby:
    executor: ruby
    steps:
      - checkout
      - run:
          name: Lint Ruby
          command: |
            gem install cookstyle --no-document
            cookstyle

workflows:
  check:
    jobs:
      - kitchen/danger:
          name: danger
          context: Danger
      - lint_ruby:
          name: Lint Ruby
